### ISSUE TITLE
Kill process - process not found when exception was thrown

### ISSUE THREAD

**Issue by hANSIc99** [hANSIc99/Pythonic#26]
Exception is thrown when using kill process button and #25 was thrown before

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Pythonic/main.py", line 327, in killProcesses
    self.grd_ops_arr[self.wrk_tab_index].kill_proc()
  File "/usr/local/lib/python3.7/site-packages/Pythonic/executor.py", line 238, in kill_proc
    os.kill(proc, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Pythonic/main.py", line 327, in killProcesses
    self.grd_ops_arr[self.wrk_tab_index].kill_proc()
  File "/usr/local/lib/python3.7/site-packages/Pythonic/executor.py", line 238, in kill_proc
    os.kill(proc, signal.SIGTERM)
ProcessLookupError: [Errno 3] No such process
```

**Comment by hANSIc99** [comment]
Fixed in v0.17
